[RSS-24] Announcement Card Component
hack4impact-calpoly/rise-stand-strong pull request #16
Opened 2021-01-27 03:26 UTC by esauerbo

<img width="430" alt="Screen Shot 2021-01-27 at 2 22 20 PM" src="https://user-images.githubusercontent.com/70536670/105938349-477a3f00-600c-11eb-89bf-0d149d308af4.png">

Created announcement card component.

2021-01-30 00:18 UTC, ellabuysse reviewed
Looks good!

2021-01-31 01:41 UTC, jackfales commented on src/components/AnnouncementCard/AnnouncementCard.css
> +  }
Can you delete this file? I don't think it's doing anything because you used Bootstrap

2021-01-31 01:42 UTC, jackfales requested changes
Looks good! Just delete the .css file I commented on and re-request my review and I'll approve it.

2021-02-01 18:50 UTC, jackfales approved these changes
Looks good! Great work.

2021-02-01 18:51 UTC, merged