[RSS-66] Implement NewAccount page
hack4impact-calpoly/rise-stand-strong pull request #53
Opened 2021-04-12 07:53 UTC by ObjectJosh

### Version Overview:
- Testing settings: Ran on localhost, browser: Chrome, Chrome simulator: iPhoneX
- Styled New Account page accordingly to mockups: again, as close fit as I could in the iPhoneX screen size dimensions, specifically
- New file: `fonts.css` in `src/components/NewAccountPage` to import font family based off mockups... I wasn't sure where to put/import it from, so please advise if I can relocate this font import
- New file and edits: `RISE_Logo.svg` to `src/components/NavBar` from JP's PR, and added this logo to the navbar (you can fix this as well)
- File edits: Added code to `package-lock.js` and `package.json` (same exact from JP's PR) in order to use font awesome icons

### Notes:
- `NewAccountPage`: Probably will need a lot of editing, since I wasn't sure if we're using responsive sizing according to screen width
- `NewAccountPage`: Commented out "Confirm Password" instead of deleting, to confirm with you if we need this "Confirm Password" field or not (wasn't on the mockups)
- `NewAccountPage`: Commented out the placeholder text for each text field instead of deleting, to confirm with you if we need this or not (wasn't on the mockups)
- `NewAccountPage`: Hide/Show password button feature needs functionality implementing, since I just added it in this version(button does not work yet).
- `NewAccountPage`: (Small note) Wasn't sure if we preferred "First name" over "First Name" or like "Phone number" over "Phone Number" (capitalization differences) so I attached a picture for each format, and you can choose which you prefer

### Visual:
<img width="680" alt="NewAccountPageVisual" src="https://user-images.githubusercontent.com/42549561/114359856-4182fd00-9b29-11eb-9c08-b362d625c5f4.png">

### Uppercase vs. Lowercase:
<img width="680" alt="UppercaseTitles" src="https://user-images.githubusercontent.com/42549561/114359922-4f388280-9b29-11eb-98c0-23206c73b414.png">
<img width="680" alt="LowercaseTitles" src="https://user-images.githubusercontent.com/42549561/114359913-4e075580-9b29-11eb-8400-1b310a57d1a6.png">

2021-04-12 19:09 UTC, jackfales commented on src/components/NewAccountPage/NewAccountPage.jsx
>                 />
Wrap the Last Name Form.Group into its own Form.Row. This way for now on Desktop it looks a bit nicer.

2021-04-12 19:10 UTC, jackfales commented on src/components/NewAccountPage/NewAccountPage.jsx
> +               </StyledHideButton>
Make sure this button is always at the right end of the password input field. This can be done using flex-end from flexbox.

2021-04-12 19:11 UTC, jackfales commented on src/components/NewAccountPage/NewAccountPage.jsx
> +         <SubmitButton type="submit">Register</SubmitButton>
This button is improperly placed when I run the app on my phone.
![IMG_0407](https://user-images.githubusercontent.com/46923410/114448271-2eebe080-9b88-11eb-97e6-8ad9bc6a5099.PNG)

2021-04-12 19:14 UTC, jackfales requested changes
Really good job Josh. Your component is mostly responsive. A couple notes:

- Feel free to remove all confirmPassword code, it's no longer needed
- If you can, implement the show/hide password functionality. This can be done by setting the type prop of that input field to "password" for hide and "text" for show. The eye icon should have an onClick handler that changes the state of that prop. Let me know if you need help with it.
- Check all comments, for the most part it looks good.
- Rerequest my review when changes are made.

2021-04-13 05:45 UTC, ObjectJosh commented
Still can't figure out why `justify-content: flex-end;` isn't working. Pushing what I have so far... fixed all errors except:
- flex-end
- when you click the "Hide/Show" button, it highlights the button in blue when it's focused. Couldn't figure out how to get rid of that

2021-04-15 20:59 UTC, jackfales commented on src/components/NewAccountPage/NewAccountPage.jsx
> +                     <FontAwesomeIcon icon={faEyeSlash} />
I don't think you need two different icons, just use the same icon but on click it toggles show password. Also did you figure out how to align it properly on the right?

2021-04-15 21:00 UTC, jackfales reviewed
Button and eye icon still look weird. Other than that looks good.
![IMG_0425](https://user-images.githubusercontent.com/46923410/114937678-f13ec000-9df2-11eb-85a9-8eed0422d18c.PNG)

2021-04-16 04:44 UTC, jackfales approved these changes
Looks good! Thanks for implementing my comments.

2021-04-16 04:44 UTC, merged