[RSS-19] Create NavBar Component
hack4impact-calpoly/rise-stand-strong pull request #9
Opened 2021-01-21 01:04 UTC by ellabuysse

Added NavBar component and minimalistic styling.

2021-01-21 05:50 UTC, jackfales requested changes
Change .html file to .jsx, otherwise everything looks great! Good job following proper naming conventions for your PR.

2021-01-21 05:50 UTC, jackfales commented on src/components/NavBar/NavBar.html
> +</html>
Can you change this to a .jsx file? Check LoginPage.jsx for inspiration. Sorry I didn't specify this earlier, but it should be a quick change.

2021-01-23 05:24 UTC, jackfales commented on src/components/NavBar/NavBar.jsx
> +  </div>
```suggestion
  return(
  <div className="navbar">
    <a href="/">Logout</a>
    <a href="/">Edit Profile</a>
  </div>
  );
```

2021-01-23 05:24 UTC, jackfales commented on src/components/NavBar/NavBar.jsx
> +export default () => (
```suggestion
export default () => {
```

2021-01-23 05:24 UTC, jackfales commented on src/components/NavBar/NavBar.jsx
> +);
```suggestion
};
```

2021-01-23 05:24 UTC, jackfales reviewed
Nice work! Just some minor changes so the file is easier to modify in the future and it should be good to go!

2021-01-23 05:25 UTC, jackfales approved these changes

2021-01-25 06:30 UTC, ObjectJosh commented
Looks good!

2021-01-25 06:30 UTC, merged